CREATE TABLE refresh_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE password_reset_tokens(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE customers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name text NOT NULL, document text, email text, phone text, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cash_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, branch_id uuid NOT NULL REFERENCES branches(id), user_id uuid NOT NULL REFERENCES users(id), opening_amount numeric(14,2) NOT NULL DEFAULT 0, closing_amount numeric(14,2), status text NOT NULL DEFAULT 'OPEN', opened_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz);
CREATE TABLE cash_movements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, cash_session_id uuid NOT NULL REFERENCES cash_sessions(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), kind text NOT NULL, amount numeric(14,2) NOT NULL, note text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE receivables(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, customer_id uuid REFERENCES customers(id), sale_id uuid REFERENCES sales(id), amount numeric(14,2) NOT NULL, paid_amount numeric(14,2) NOT NULL DEFAULT 0, due_date date, status text NOT NULL DEFAULT 'OPEN', created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_id uuid REFERENCES customers(id);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cancelled_at timestamptz;
CREATE INDEX idx_refresh_user ON refresh_sessions(user_id,expires_at); CREATE INDEX idx_customers_tenant ON customers(tenant_id); CREATE INDEX idx_cash_tenant ON cash_sessions(tenant_id,opened_at); CREATE INDEX idx_receivables_tenant ON receivables(tenant_id,status);
